<script setup>
import { onMounted, ref } from 'vue'
const props=defineProps({request:Function})
const records=ref([]),record=ref(null),files=ref([]),academicYear=ref('2025-2026'),className=ref(''),busy=ref(false),error=ref(''),note=ref('')
function editable(item){const copy=structuredClone(item);for(const sheet of copy.payload.sheets)for(const row of sheet.students)row.score_text=(row.scores||[]).join(',');return copy}
async function load(){records.value=await props.request('/class-rankings')}
async function open(item){record.value=editable(await props.request(`/class-rankings/${item.id}`))}
async function upload(){if(files.value.length<2){error.value='请至少选择两张成绩单图片';return}busy.value=true;error.value='';try{const body=new FormData();for(const file of files.value)body.append('files',file);body.append('academic_year',academicYear.value);body.append('class_name',className.value);record.value=editable(await props.request('/class-rankings',{method:'POST',body}));await load();note.value='OCR 已完成，请逐行核对后确认排名。'}catch(e){error.value=e.message}finally{busy.value=false}}
function addRow(sheet){sheet.students.push({student_id:'',name:'',scores:[],score_text:'',reported_average:null,reported_total:null,reported_rank:null,ocr_confidence:null})}
async function confirm(){busy.value=true;error.value='';try{const sheets=record.value.payload.sheets.map(sheet=>({...sheet,students:sheet.students.map(({score_text,...row})=>({...row,scores:score_text.split(/[,，\s]+/).filter(Boolean).map(Number)}))}));record.value=editable(await props.request(`/class-rankings/${record.value.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({sheets,rank_method:'competition'})}));await load();note.value='年度平均分和班级排名已确认。'}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section class="academic-view"><h1>班级成绩排名</h1><p class="muted">上传同一班级、同一学年的多张成绩单图片。系统按学号合并所有学期课程，计算年度算术平均分并排序。</p><p v-if="error" class="inline-error" role="alert">{{error}}</p><p v-if="note" role="status">{{note}}</p>
<article class="academic-card"><h2>上传成绩单图片</h2><div class="academic-form-row"><label>学年<input v-model="academicYear" /></label><label>班级<input v-model="className" placeholder="例如：计科23-A1" /></label></div><label class="upload-button">选择图片<input type="file" accept=".png,.jpg,.jpeg,.webp" multiple @change="files=[...$event.target.files]" /></label><p class="muted">已选择 {{files.length}} 张。图片只用于本次 OCR，不保存原图。</p><button class="primary-button" :disabled="busy||files.length<2||!className" @click="upload">{{busy?'正在识别…':'开始识别'}}</button></article>
<article v-if="records.length" class="academic-card"><h2>历史任务</h2><button v-for="item in records" :key="item.id" class="policy-item" @click="open(item)"><strong>{{item.payload.ranking?.class_name||'待识别班级'}}</strong><span>{{item.payload.ranking?.academic_year}} · {{item.status==='confirmed'?'已确认':'待校对'}}</span></button></article>
<template v-if="record"><article v-for="sheet in record.payload.sheets" :key="`${sheet.term}-${sheet.source_name}`" class="academic-card"><div class="report-heading"><div><h2>{{sheet.class_name}} · 第 {{sheet.term}} 学期</h2><p class="muted">{{sheet.source_name}}，识别 {{sheet.students.length}} 人</p></div><select v-model.number="sheet.term"><option :value="1">第一学期</option><option :value="2">第二学期</option><option :value="3">第三学期</option></select></div><p v-for="warning in sheet.warnings" :key="warning" class="academic-warning">{{warning}}</p><div class="table-scroll"><table><thead><tr><th>学号</th><th>姓名</th><th>课程成绩（逗号分隔）</th><th>表内平均分</th><th>OCR</th><th></th></tr></thead><tbody><tr v-for="(row,index) in sheet.students" :key="`${row.student_id}-${index}`"><td><input v-model="row.student_id" /></td><td><input v-model="row.name" /></td><td><input v-model="row.score_text" /></td><td>{{row.reported_average??'—'}}</td><td>{{row.ocr_confidence==null?'人工':`${(row.ocr_confidence*100).toFixed(1)}%`}}</td><td><button @click="sheet.students.splice(index,1)">移除</button></td></tr></tbody></table></div><button @click="addRow(sheet)">补录学生</button></article>
<article class="academic-card"><div class="report-heading"><div><h2>年度排名预览</h2><p class="muted">仅完整出现在全部学期的学生参与排名；相同平均分使用并列排名。</p></div><button class="primary-button" :disabled="busy" @click="confirm">核对完成并重新计算</button></div><div class="table-scroll"><table><thead><tr><th>排名</th><th>学号</th><th>姓名</th><th>课程数</th><th>年度总分</th><th>年度平均分</th><th>完整性</th></tr></thead><tbody><tr v-for="row in record.payload.ranking.rows" :key="row.student_id"><td>{{row.rank??'—'}}</td><td>{{row.student_id}}</td><td>{{row.name}}</td><td>{{row.course_count}}</td><td>{{row.total_score}}</td><td><strong>{{row.annual_average??'—'}}</strong></td><td>{{row.complete?'完整':`缺少第 ${row.missing_terms.join('、')} 学期`}}</td></tr></tbody></table></div><p class="muted">{{record.payload.notice}}</p></article></template></section></template>
