<script setup>
import {ref,onMounted} from 'vue'
const props=defineProps({request:Function,user:Object})
const rows=ref([]),selected=ref(null),error=ref(''),note=ref(''),busy=ref(false),file=ref(null),editor=ref('')
const metadata=ref({title:'',school:'新疆工程学院',scholarship:'国家奖学金',selection_year:new Date().getFullYear(),academic_year:'',audience:'本校本科生'})
const defaults={source_url:'',effective_from:null,effective_until:null,application_start:null,application_end:null,deadlines:[],quotas:[],clauses:[],common_rules:[],branches:[],materials:[],steps:[],course_categories:[],missing_attachments:[],conflicts:[],reviewed:false}
const json=body=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
async function load(){rows.value=await props.request('/policies')}
function open(row){selected.value=row; const {filename,path,original,attachments,...draft}=row.payload;editor.value=JSON.stringify(draft,null,2)}
async function upload(){busy.value=true;error.value='';try{const body=new FormData();body.append('file',file.value);body.append('metadata',JSON.stringify({...defaults,...metadata.value,selection_year:Number(metadata.value.selection_year)}));open(await props.request('/policies',{method:'POST',body}));await load()}catch(e){error.value=e.message}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';try{const data=JSON.parse(editor.value);open(await props.request(`/policies/${selected.value.id}`,{...json(data),method:'PUT'}));await load();note.value='已保存草稿。'}catch(e){error.value=e.message}finally{busy.value=false}}
async function extract(){busy.value=true;error.value='';try{const data=await props.request(`/policies/${selected.value.id}/extract`,json({}));editor.value=JSON.stringify(data.draft,null,2);note.value=data.message}catch(e){error.value=e.message}finally{busy.value=false}}
async function activate(){busy.value=true;error.value='';try{await props.request(`/policies/${selected.value.id}/activate`,json({}));await load();selected.value=null;note.value='政策版本已启用。'}catch(e){error.value=e.message}finally{busy.value=false}}
async function attach(event){const attachment=event.target.files[0];if(!attachment)return;busy.value=true;try{const body=new FormData();body.append('file',attachment);open(await props.request(`/policies/${selected.value.id}/attachments`,{method:'POST',body}));await load()}catch(e){error.value=e.message}finally{busy.value=false;event.target.value=''}}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section class="academic-view"><h1>政策库</h1><p class="muted">按奖学金、评选年度和考核学年管理原文与评审依据。</p><p v-if="error" class="inline-error" role="alert">{{error}}</p><p v-if="note" role="status">{{note}}</p>
  <article v-if="user.role==='admin'" class="academic-card"><h2>导入真实政策</h2><form @submit.prevent="upload"><div class="academic-form-row"><label v-for="(label,key) in {title:'通知标题',school:'学校',scholarship:'奖学金',selection_year:'评选年度',academic_year:'考核学年',audience:'适用对象'}" :key="key">{{label}}<input v-model="metadata[key]" :type="key==='selection_year'?'number':'text'" required /></label></div><input type="file" accept=".pdf,.docx,.txt,.md,.xls,.xlsx" required @change="file=$event.target.files[0]" /><button class="primary-button" :disabled="busy">上传为草稿</button></form><p class="muted">先导入通知及评审办法完整原文，再核对规则。含缺失附件或冲突的草稿无法启用。</p></article>
  <article class="academic-card"><h2>政策版本</h2><p v-if="!rows.length">尚未导入适用政策。真实通知提供后，由管理员导入并核对。</p><button v-for="row in rows" :key="row.id" class="policy-item" @click="open(row)"><strong>{{row.payload.title}}</strong><span>{{row.payload.selection_year}} 年评选 / {{row.payload.academic_year}} 学年 · {{({draft:'待核对',active:'已启用',superseded:'已被新版本替代'})[row.status]}}</span></button></article>
  <article v-if="selected" class="academic-card"><h2>{{selected.payload.title}}</h2><p>适用对象：{{selected.payload.audience}}</p><details open><summary>政策原文</summary><div v-for="(page,i) in selected.payload.original" :key="i"><h4>{{page.locator}}</h4><p class="policy-original">{{page.text}}</p></div></details>
    <template v-if="user.role==='admin' && selected.status==='draft'"><label>追加评审办法或附件<input type="file" accept=".pdf,.docx,.txt,.md,.xls,.xlsx" :disabled="busy" @change="attach" /></label><h3>规则草稿</h3><p>模型可辅助提取，启用前需对照原文逐项检查。common_rules 为全部必需条件；branches 为满足任一分支。比例阈值使用 0～1。</p><button :disabled="busy" @click="extract">辅助提取规则</button><label class="rule-editor-label">结构化规则编辑器<textarea v-model="editor" class="rule-editor" rows="24" spellcheck="false"></textarea></label><p>核对完成后将 reviewed 设为 true，先保存，再启用。材料、步骤和规则必须引用原文条款编号。</p><button :disabled="busy" @click="save">保存草稿</button> <button class="primary-button" :disabled="busy || !selected.payload.reviewed" @click="activate">启用已核对版本</button></template>
  </article>
</section></template>
