<script setup>
import { ref, onMounted } from 'vue'
const props = defineProps({ request: Function, user: Object })
const users=ref([]), classes=ref([]), colleges=ref([]), students=ref([]), audit=ref([]), profile=ref(null), error=ref(''), note=ref(''), busy=ref(false), query=ref(''), selected=ref('')
const roles={student:'学生',teacher:'教师',counselor:'辅导员',academic_admin:'学院管理员',admin:'系统管理员'}
const staff=ref({username:'',name:'',password:'',role:'teacher',college_code:'',managed_classes:[]})
const access=ref({role:'student',college_code:'',managed_classes:[],class_name:''})
const newClass=ref({name:'',college_code:''})
const json=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})
async function load(){classes.value=await props.request('/classes');students.value=await props.request('/management/students');if(props.user.role==='admin'){users.value=await props.request(`/admin/users?q=${encodeURIComponent(query.value)}`);audit.value=await props.request('/admin/audit');colleges.value=(await props.request('/catalog/colleges')).items}}
function choose(){const row=users.value.find(x=>x.id===Number(selected.value));if(row)access.value={role:row.role,college_code:row.college_code||'',managed_classes:row.managed_classes||[],class_name:row.class_name||''}}
async function run(action){busy.value=true;error.value='';note.value='';try{await action();await load();note.value='操作已完成'}catch(e){error.value=e.message}finally{busy.value=false}}
async function createStaff(){await run(async()=>{await props.request('/admin/users',json('POST',{...staff.value,managed_classes:staff.value.role==='counselor'?staff.value.managed_classes:[]}));staff.value.password='';staff.value.username='';staff.value.name=''})}
async function saveAccess(){await run(()=>props.request(`/admin/users/${selected.value}/access`,json('PATCH',{...access.value,managed_classes:access.value.role==='counselor'?access.value.managed_classes:[],class_name:access.value.role==='student'?access.value.class_name:''})))}
async function viewProfile(id){await run(async()=>{profile.value=null;profile.value=await props.request(`/management/students/${id}/profile`)})}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section class="academic-view"><h1>账号与数据管理</h1><p class="muted">只展示你负责范围内的学生与班级。档案查看及授权操作会留存审计记录。</p><p v-if="error" class="inline-error" role="alert">{{error}}</p><p v-if="note" role="status">{{note}}</p>
<template v-if="user.role==='admin'">
<form class="academic-card" @submit.prevent="run(()=>request('/admin/classes',json('POST',newClass)))"><h2>登记班级</h2><div class="academic-form-row"><label>班级名称<input v-model="newClass.name" required maxlength="120" /></label><label>所属学院<select v-model="newClass.college_code" required><option value="">选择学院</option><option v-for="item in colleges" :key="item.code" :value="item.code">{{item.name}}</option></select></label></div><button :disabled="busy">登记班级</button></form>
<form class="academic-card" @submit.prevent="createStaff"><h2>创建工作人员账号</h2><div class="academic-form-row"><label>用户名<input v-model="staff.username" required pattern="[A-Za-z0-9_]{3,40}" autocomplete="off" /></label><label>姓名<input v-model="staff.name" required /></label><label>初始密码<input v-model="staff.password" required minlength="12" maxlength="256" type="password" autocomplete="new-password" /></label><label>角色<select v-model="staff.role"><option v-for="key in ['teacher','counselor','academic_admin','admin']" :key="key" :value="key">{{roles[key]}}</option></select></label><label>学院<select v-model="staff.college_code"><option value="">未指定</option><option v-for="item in colleges" :key="item.code" :value="item.code">{{item.name}}</option></select></label></div><fieldset v-if="staff.role==='counselor'"><legend>负责班级</legend><label v-for="item in classes" :key="item.name"><input type="checkbox" v-model="staff.managed_classes" :value="item.name" />{{item.name}}</label></fieldset><button :disabled="busy">创建账号</button></form>
<form class="academic-card" @submit.prevent="saveAccess"><h2>调整授权与学生班级</h2><div class="academic-form-row"><label>筛选用户名<input v-model="query" /></label><button type="button" :disabled="busy" @click="run(load)">查询</button><label>账号<select v-model="selected" required @change="choose"><option value="">选择账号</option><option v-for="item in users.filter(x=>x.id!==user.id)" :key="item.id" :value="item.id">{{item.username}} · {{item.name}}</option></select></label><label>角色<select v-model="access.role"><option v-for="(name,key) in roles" :key="key" :value="key">{{name}}</option></select></label><label>学院<select v-model="access.college_code"><option value="">未指定</option><option v-for="item in colleges" :key="item.code" :value="item.code">{{item.name}}</option></select></label><label v-if="access.role==='student'">所属班级<select v-model="access.class_name"><option value="">未分配</option><option v-for="item in classes.filter(x=>x.college_code===access.college_code)" :key="item.name" :value="item.name">{{item.name}}</option></select></label></div><fieldset v-if="access.role==='counselor'"><legend>负责班级（取消勾选将撤销权限）</legend><label v-for="item in classes" :key="item.name"><input type="checkbox" v-model="access.managed_classes" :value="item.name" />{{item.name}}</label></fieldset><button :disabled="busy||!selected">保存授权</button></form>
</template>
<article class="academic-card"><h2>负责范围内的学生</h2><div class="table-scroll"><table><thead><tr><th>姓名</th><th>学院 / 专业</th><th>年级 / 班级</th><th></th></tr></thead><tbody><tr v-for="student in students" :key="student.id"><td>{{student.name}}</td><td>{{student.college}} / {{student.major}}</td><td>{{student.grade}} / {{student.class_name||'未分配'}}</td><td><button :disabled="busy" @click="viewProfile(student.id)">查看已确认档案</button></td></tr></tbody></table></div><p v-if="!students.length" class="muted">当前没有负责范围内的学生。</p></article>
<article v-if="profile" class="academic-card"><h2>学生档案 · {{profile.user_id}}</h2><p>{{profile.payload.facts.college?.value}} · {{profile.payload.facts.major?.value}} · {{profile.payload.facts.class_name?.value}}</p><div class="table-scroll"><table><thead><tr><th>学年</th><th>课程</th><th>学分</th><th>成绩</th></tr></thead><tbody><tr v-for="(course,index) in profile.payload.courses" :key="index"><td>{{course.academic_year}}</td><td>{{course.name}}</td><td>{{course.credits}}</td><td>{{course.score}}</td></tr></tbody></table></div></article>
<details v-if="user.role==='admin'" class="academic-card"><summary>最近 100 条管理审计</summary><p v-for="row in audit" :key="row.id">{{row.created_at}} · 操作者 {{row.actor_id}} · {{row.action}} · 对象 {{row.target}}</p></details>
</section></template>
<style scoped>.academic-card{margin:18px 0}fieldset{margin:12px 0;border:1px solid #dde1e7}fieldset label{display:inline-flex;align-items:center;margin:6px 12px}fieldset input{width:auto;margin-right:6px}</style>
